language: node_js
node_js:
- '7'
cache: npm
before_install:
- npm i
install:
- npm run build
- mkdir deploy
- cp index.html deploy/
- cp -r dist deploy/
- cp -r styles deploy/
- cp -r assets deploy/
deploy:
  local_dir: deploy
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: IVOaKOG7hsiDDektNFn3VsvuvhHY79HyzqfEoLJKE63IvdsOQFuX5ii/QXrHG0jJ+O6l59JOOlB1VRbEneGiqcCtblemjluYo4G4+GTWqC3IVr93sdgC+/U9j5ZSj1C5ZP+gXv239a6haNQinKo68hIcSX6J6ZIFQ7O96alOsMnXYLiDKm4N5DivjTK3VPy9F+Yy3SZA8kGywO4BcRMoqPAeqC1VIxHG4if/y+S5dAUKhiQYK7TSuYiOAhaNfsKX+wuVTLsdVX4IUnwJepXLnathZwEU24UNzyQw68Pf7nWx+7qKbaC2yNAyWrbV6DgE/tGd/J/M7thasoCe0qbf1URl2UL2GwaT8tg+Wds0qoWBDOwDn7SxuiTOT/Vk+HyxYUvLMFTabXbX87lTwg8JPQXqNqklnkFQW7pBeXQFUHIYn4xLQ5WoBs9rVdss47BCUzjJX6EAKMmouR5/FNaUocmLtmAYB2GHFTXsPj6wY5JVc40JMOCAIyFh/yOOXcnVFxzmBeJsFTys6Jj+zi+HL1XsOO8KeucWrhcTQc9kO+R50QeR98EBsShhPwcrXOn2Vlh0nVwTj+jwGlrJN+CafqQK3l3bjV2qewImmotcvTJ9J+c+JYn99/68+vVzsx+vbMLyj7F6DMeaSMMLPOx/yJzm6nO/7AjByosctWfuS44=
