language: node_js
node_js:
  - "7"
cache: npm
before_install:
  - npm i
install:
  - npm run build
  - bash deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master