language: node_js
node_js:
- '7'
cache: npm
before_install:
- npm i
install:
- npm run build
- bash deploy.sh
deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
